### Load all packages needed for project.

# devtools::install_github("ebenmichael/augsynth")
library(augsynth)
library(here)
library(doParallel)
library(estimatr)
library(glmnet)
library(grf)
library(gsynth)
library(keras)
library(MatchIt)
# devtools::install_github("susanathey/MCPanel")
library(MCPanel)
library(microsynth)
library(randomForest)
library(sf)
library(tidyverse)
library(tidyquant)
library(zoo)
